platform :ios, '13.0'
use_frameworks!

target 'iTunes-Music' do
  pod 'IGListKit'
  pod 'SnapKit'
  pod 'Localize-Swift'
  pod 'Toast-Swift'
  pod 'SDWebImage', '~> 5.0'

  # Pods for iTunes-Music

  target 'iTunes-MusicTests' do
	pod 'LayoutTest/Swift'
  end

  target 'iTunes-MusicUITests' do
  end

end
