platform :ios, '13.0'
use_frameworks!

target 'iTunes-Music' do
  pod 'IGListKit' , '~> 4.0.0'
  pod 'SnapKit' , '~> 5.6.0'
  pod 'Localize-Swift' , '~> 3.2'
  pod 'Toast-Swift' , '~> 5.0.1'
  pod 'SDWebImage', '~> 5.0'

  # Pods for iTunes-Music
  target 'iTunes-MusicTests' do
	pod 'LayoutTest/Swift'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end